/**
 * RCS blue-white theme layer. Every token carries both schemes so following
 * the host's light/dark/system preference never leaves an unreadable value.
 * Semantic error, success, and warning colors intentionally remain untouched.
 */
export const rcsThemeTokens = Object.freeze({
  '--dsw-alias-bg-base': { light: '#f4f8ff', dark: '#071426' },
  '--dsw-alias-bg-layer-1': { light: '#f8fbff', dark: '#0b1b32' },
  '--dsw-alias-bg-layer-2': { light: '#f0f5ff', dark: '#0f2340' },
  '--dsw-alias-bg-layer-3': { light: '#ffffff', dark: '#132b4b' },
  '--dsw-alias-bg-module-platform': { light: '#edf3ff', dark: '#0d203b' },
  '--dsw-alias-bg-multi-select': { light: '#e7f0ff', dark: '#163258' },
  '--dsw-alias-bg-overlay': { light: '#dce8fb', dark: '#1b3a66' },
  '--dsw-alias-border-l1': { light: 'rgba(30,91,198,.10)', dark: 'rgba(169,197,255,.10)' },
  '--dsw-alias-border-l2': { light: 'rgba(30,91,198,.20)', dark: 'rgba(169,197,255,.20)' },
  '--dsw-alias-border-l3': { light: 'rgba(30,91,198,.28)', dark: 'rgba(169,197,255,.28)' },
  '--dsw-alias-border-l4': { light: 'rgba(30,91,198,.38)', dark: 'rgba(169,197,255,.38)' },
  '--dsw-alias-brand-primary': { light: '#1e5bc6', dark: '#8eb7ff' },
  '--dsw-alias-brand-primary-invert': { light: '#ffffff', dark: '#081426' },
  '--dsw-alias-brand-primary-new-colorprimary-new-color': { light: '#2864dc', dark: '#8eb7ff' },
  '--dsw-alias-brand-text': { light: '#174ea6', dark: '#a9c5ff' },
  '--dsw-alias-button-contrast-fill': { light: '#174a9e', dark: '#dce9ff' },
  '--dsw-alias-button-elevated-fill': { light: '#ffffff', dark: '#163258' },
  '--dsw-alias-button-floating-fill': { light: '#ffffff', dark: '#102b50' },
  '--dsw-alias-button-floating-hover': { light: '#e5efff', dark: '#18385f' },
  '--dsw-alias-button-ghost-active-border': { light: '#89a9db', dark: '#5b80ad' },
  '--dsw-alias-button-ghost-active-fill': { light: '#dce9ff', dark: '#18385f' },
  '--dsw-alias-button-ghost-active-hover': { light: '#cfe0ff', dark: '#1b3a66' },
  '--dsw-alias-button-primary-fill': { light: '#1e5bc6', dark: '#8eb7ff' },
  '--dsw-alias-button-primary-hover': { light: '#174a9e', dark: '#a9c5ff' },
  '--dsw-alias-button-primary-dimmed': { light: '#cfddf7', dark: '#29486f' },
  '--dsw-alias-button-info-fill': { light: '#2864dc', dark: '#6c9dff' },
  '--dsw-alias-button-info-hover': { light: '#1f55b9', dark: '#8eb7ff' },
  '--dsw-alias-interactive-bg-hover': { light: 'rgba(40,100,220,.08)', dark: 'rgba(142,183,255,.10)' },
  '--dsw-alias-interactive-bg-hover-accent': { light: 'rgba(40,100,220,.16)', dark: 'rgba(142,183,255,.20)' },
  '--dsw-alias-interactive-bg-hover-solid': { light: '#e5efff', dark: '#173255' },
  '--dsw-alias-interactive-bg-active': { light: 'rgba(40,100,220,.18)', dark: 'rgba(142,183,255,.24)' },
  '--dsw-alias-label-primary': { light: '#102a54', dark: '#f5f9ff' },
  '--dsw-alias-label-secondary': { light: '#36557f', dark: '#cadbfa' },
  '--dsw-alias-label-tertiary': { light: '#58708f', dark: '#91a9cc' },
  '--dsw-alias-label-caption': { light: '#566d89', dark: '#8ba4c8' },
  '--dsw-alias-label-dimmed': { light: '#b7c5d8', dark: '#496582' },
  '--dsw-alias-label-primary-foreground': { light: '#ffffff', dark: '#081426' },
  '--dsw-alias-label-primary-inverted': { light: '#ffffff', dark: '#081426' },
  '--dsw-alias-label-primary-bluish': { light: '#174ea6', dark: '#c7dbff' },
  '--dsw-alias-markdown-citation': { light: '#dce9ff', dark: '#173255' },
  '--dsw-alias-markdown-code-block-banner': { light: '#e7f0ff', dark: '#0b1b32' },
  '--dsw-alias-markdown-code-block': { light: '#f0f5ff', dark: '#08182d' },
  '--dsw-alias-markdown-inline-code': { light: '#e1ecff', dark: '#173255' },
  '--dsw-alias-markdown-placeholder': { light: '#edf3ff', dark: '#0d203b' },
  '--dsw-alias-markdown-tag': { light: '#e7f0ff', dark: '#173255' },
  '--dsw-alias-scrollbar-bg-l1': { light: '#c8d8f2', dark: '#29486f' },
  '--dsw-alias-scrollbar-bg-l2': { light: '#b6caeb', dark: '#34577f' },
  '--dsw-alias-scrollbar-hover-l1': { light: '#9eb9e5', dark: '#466b99' },
  '--dsw-alias-scrollbar-hover-l2': { light: '#89a9db', dark: '#5b80ad' },
  '--dsw-alias-state-business-primary': { light: '#2864dc', dark: '#8eb7ff' },
  '--dsw-alias-state-business-tertiary': { light: '#dbe8ff', dark: '#173b6b' },
  '--dsw-alias-toast-bg': { light: '#174174', dark: '#1e4478' },
  '--dsw-alias-tooltip-bg': { light: '#102f5c', dark: '#1e4478' },
  '--dsw-specific-bubble': { light: '#eaf3ff', dark: '#102b50' },
  '--dsw-specific-bubble-highlight': { light: '#d6e6ff', dark: '#174379' },
  '--dsw-specific-input-major': { light: '#ffffff', dark: '#0f2340' },
  '--dsw-specific-login-input': { light: '#f4f8ff', dark: '#08182d' },
  '--dsw-specific-menu': { light: '#ffffff', dark: '#132b4b' },
  '--dsw-specific-selector': { light: '#e7f0ff', dark: '#163258' },
  '--dsw-specific-sidebar-fill': { light: '#eaf2ff', dark: '#071a31' },
  '--dsw-specific-sidebar-nav-item-active-accent': { light: '#cfe0ff', dark: '#174379' },
  '--dsw-specific-sidebar-nav-item-active': { light: '#dce9ff', dark: '#18385f' },
  '--dsw-specific-sidebar-nav-item-hover': { light: '#e5efff', dark: '#102b50' },
  '--dsw-specific-tip': { light: '#edf3ff', dark: '#0d203b' },
})

/** Install a lifecycle-bound theme layer; disabling the plugin restores host tokens. */
export function installRcsTheme(ctx) {
  ctx.effect(
    () => ctx.theme.overrideTokens('rcs-blue-white', rcsThemeTokens),
    'rcs-ui-client: RCS blue-white theme layer',
  )
}
